from omegaconf import OmegaConf


cfg = {
    "device": "cuda",
    "dtype": "float32",
    "autocast": True,
    "autocast_dtype": "float16",
    "seed": 2036,
    "show": False,
    "continue_from": None,
    "execute_only": None,
    "execute_inplace": False,
    "benchmark_no_load": False,
    "efficient_attention_backend": "xformers",
    "num_threads": 1,
    "mp_start_method": "forkserver",
    "label": None,
    "logging": {"level": "INFO", "log_updates": 10, "log_tensorboard": True, "log_wandb": False},
    "tensorboard": {"with_media_logging": False, "name": None, "sub_dir": None},
    "wandb": {"with_media_logging": True, "project": "audiocraft-jamendo-new", "name": None, "group": None},
    "slurm": {
        "gpus": 4,
        "mem_per_gpu": 40,
        "time": 3600,
        "constraint": None,
        "partition": None,
        "comment": None,
        "setup": [],
        "exclude": "",
    },
    "dora": {
        "dir": "/checkpoint/${oc.env:USER}/experiments/audiocraft/outputs",
        "exclude": [
            "device",
            "wandb.*",
            "tensorboard.*",
            "logging.*",
            "dataset.num_workers",
            "eval.num_workers",
            "special.*",
            "metrics.visqol.bin",
            "metrics.fad.bin",
            "execute_only",
            "execute_best",
            "generate.every",
            "optim.eager_sync",
            "profiler.*",
            "deadlock.*",
            "efficient_attention_backend",
            "num_threads",
            "mp_start_method",
        ],
        "use_rendezvous": False,
        "git_save": True,
    },
    "datasource": {
        "max_sample_rate": 48000,
        "max_channels": 2,
        "train": "/home/nate/morecode/audiocraft/egs/splice",
        "valid": "/home/nate/morecode/audiocraft/egs/splice",
        "evaluate": "/home/nate/morecode/audiocraft/egs/splice",
        "generate": "/home/nate/morecode/audiocraft/egs/splice",
    },
    "solver": "magnet",
    "fsdp": {
        "use": False,
        "param_dtype": "float16",
        "reduce_dtype": "float32",
        "buffer_dtype": "float32",
        "sharding_strategy": "shard_grad_op",
        "per_block": True,
    },
    "profiler": {"enabled": False},
    "deadlock": {"use": True, "timeout": 600},
    "dataset": {
        "batch_size": 6,
        "num_workers": 10,
        "segment_duration": 30,
        "num_samples": None,
        "return_info": True,
        "shuffle": False,
        "sample_on_duration": False,
        "sample_on_weight": False,
        "min_segment_ratio": 0.8,
        "train": {
            "num_samples": 1000000,
            "shuffle": True,
            "shuffle_seed": 0,
            "permutation_on_files": False,
            "merge_text_p": 0.25,
            "drop_desc_p": 0.5,
            "drop_other_p": 0.5,
        },
        "valid": {"num_samples": 8},
        "evaluate": {"num_samples": 10000},
        "generate": {"num_samples": 8, "return_info": True},
    },
    "checkpoint": {"save_last": True, "save_every": 50, "keep_last": 10, "keep_every_states": None},
    "generate": {
        "every": 25,
        "path": "samples",
        "audio": {"format": "wav", "strategy": "loudness", "sample_rate": "${sample_rate}", "loudness_headroom_db": 14},
        "lm": {
            "use_sampling": True,
            "temp": 3.0,
            "top_k": 0,
            "top_p": 0.9,
            "prompted_samples": False,
            "unprompted_samples": True,
            "gen_gt_samples": False,
            "prompt_duration": None,
            "gen_duration": None,
            "remove_prompts": False,
            "max_prompt_len": None,
            "max_gen_len": None,
            "max_cfg_coef": 10.0,
            "min_cfg_coef": 1.0,
            "decoding_steps": [60, 10, 10, 10],
            "anneal_temp": True,
            "span_scoring": "max",
            "span_arrangement": "nonoverlap",
            "samples": {"prompted": False, "unprompted": True},
        },
        "num_workers": 5,
    },
    "evaluate": {
        "every": 25,
        "num_workers": 5,
        "truncate_audio": None,
        "fixed_generation_duration": None,
        "metrics": {"base": False, "fad": False, "kld": False, "text_consistency": False, "chroma_cosine": False},
    },
    "optim": {
        "epochs": 500,
        "updates_per_epoch": 2000,
        "lr": 1,
        "optimizer": "dadam",
        "adam": {"betas": [0.9, 0.95], "weight_decay": 0.1, "eps": 1e-08},
        "ema": {"use": True, "updates": 10, "device": "cuda", "decay": 0.99},
        "max_norm": 1.0,
        "eager_sync": True,
    },
    "schedule": {
        "lr_scheduler": "cosine",
        "step": {"step_size": None, "gamma": None},
        "exponential": {"lr_decay": None},
        "cosine": {"warmup": 4000, "lr_min_ratio": 0.0, "cycle_length": 1.0},
        "polynomial_decay": {"warmup": None, "zero_lr_warmup_steps": 0, "end_lr": 0.0, "power": 1},
        "inverse_sqrt": {"warmup": None, "warmup_init_lr": 0.0},
        "linear_warmup": {"warmup": None, "warmup_init_lr": 0.0},
    },
    "classifier_free_guidance": {"training_dropout": 0.3, "inference_coef": 3.0},
    "attribute_dropout": {},
    "fuser": {
        "cross_attention_pos_emb": False,
        "cross_attention_pos_emb_scale": 1,
        "sum": [],
        "prepend": [],
        "cross": ["description"],
        "input_interpolate": [],
    },
    "conditioners": {
        "description": {
            "model": "t5",
            "t5": {"name": "t5-base", "finetune": False, "word_dropout": 0.3, "normalize_text": False},
        }
    },
    "sample_rate": 48000,
    "channels": 2,
    "compression_model_checkpoint": "//pretrained/facebook/encodec_32khz",
    "compression_model_n_q": None,
    "tokens": {"padding_with_special_token": False},
    "interleave_stereo_codebooks": {"use": False, "per_timestep": False},
    "cache": {"path": None, "write": False, "write_shard": 0, "write_num_shards": 1},
    "metrics": {
        "fad": {"use_gt": False, "model": "tf", "tf": {"bin": None, "model_path": "//reference/fad/vggish_model.ckpt"}},
        "kld": {"use_gt": False, "model": "passt", "passt": {"pretrained_length": 20}},
        "text_consistency": {
            "use_gt": False,
            "model": "clap",
            "clap": {
                "model_path": "//reference/clap/music_audioset_epoch_15_esc_90.14.pt",
                "model_arch": "HTSAT-base",
                "enable_fusion": False,
            },
        },
        "chroma_cosine": {
            "use_gt": False,
            "model": "chroma_base",
            "chroma_base": {"sample_rate": "${sample_rate}", "n_chroma": 12, "radix2_exp": 14, "argmax": True},
        },
    },
    "lm_model": "transformer_lm_magnet",
    "codebooks_pattern": {
        "modeling": "parallel",
        "delay": {"delays": [0, 1, 2, 3], "flatten_first": 0, "empty_initial": 0},
        "unroll": {"flattening": [0, 1, 2, 3], "delays": [0, 0, 0, 0]},
        "music_lm": {"group_by": 2},
        "coarse_first": {"delays": [0, 0, 0]},
        "parallel": {"empty_initial": -1},
    },
    "transformer_lm": {
        "dim": 1536,
        "num_heads": 24,
        "num_layers": 48,
        "hidden_scale": 4,
        "n_q": 4,
        "card": 2048,
        "dropout": 0.0,
        "emb_lr": None,
        "activation": "gelu",
        "norm_first": True,
        "bias_ff": False,
        "bias_attn": False,
        "bias_proj": False,
        "past_context": None,
        "causal": False,
        "custom": False,
        "memory_efficient": True,
        "attention_as_float32": False,
        "layer_scale": None,
        "positional_embedding": "sin",
        "xpos": False,
        "checkpointing": "none",
        "weight_init": "gaussian",
        "depthwise_init": "current",
        "zero_bias_init": True,
        "norm": "layer_norm",
        "cross_attention": False,
        "qk_layer_norm": False,
        "qk_layer_norm_cross": False,
        "attention_dropout": None,
        "kv_repeat": 1,
        "two_step_cfg": False,
        "subcodes_context": 5,
        # "compression_model_framerate": 50,
        "compression_model_framerate": 150,
        "segment_duration": 0,
        "span_len": -1,
    },
    "masking": {"span_len": 3},
}

cfg = OmegaConf.create(cfg)